name: Android Release (No Cache)

on:
  workflow_dispatch:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on:
  workflow_dispatch:

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution:
  workflow_dispatch:
          java-version:
  workflow_dispatch:

      - run: chmod +x gradlew

      - run: ./gradlew assembleRelease --no-daemon --no-build-cache --rerun-tasks

      - uses: actions/upload-artifact@v4
        with:
          name: NetMonitorApp-release
          path: app/build/outputs/apk/release/*.apk
